### ISSUE TITLE
Uploading of wave files does not work.

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#44] opened 2021-04-29 06:02 UTC
I have tried both dragging and dropping the file, and clicking the box, and selecting the wave file. Both do not work.
I did get a wave file name showing in the box once, but then it disappeared when I created a new session. 

Uploading word documents in the box above looks like it might work though (but I cannot test that since I cannot create the project without sound files).

**Comment by johanvonboer** [comment] 2021-04-29 08:01
I had a quick look at this, the documents dropzone will accept anything, but the session upload will only accept wav files and it does this by checking that the mime typ is audio/wav, although it works for me with audio/x-wav as well.

Could you check what mime type your files are by running (in a shell) `file -i audio.wav` ?

Regardless - there should of course be some sort of error message popping up explaining what the problem is when you try to drop something invalid, I'll make that happen.

**Comment by johanvonboer** [comment] 2021-04-29 08:11
Regarding your other points in this.

1. The thing about uploaded wavs disappearing when you add a session - oops! I have confirmed this and it must be a bug that introduced itself when I was restructuring how the forms work. Will of course fix that.
2. Regarding not being able to create the project without sound files - this should be possible, the only thing that's really required is a project name, everything else could be left blank. But perhaps you just meant that it would be pointless to create it without the wav files?

**Comment by johanvonboer** [comment] 2021-05-04 11:17
The thing relating to this should all be fixed now

**Closed by johanvonboer** 2021-05-04 11:17 UTC

**Comment by FredrikKarlssonSpeech** [comment] 2021-05-07 11:05
Nope, does not work (on the live platform).
The files I am trying to upload are viewed as audio/x-wav mime type.
